name: Build and Release

on:
  push:
    branches:
      - "release/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Get version from pubspec
        id: version
        run: |
          echo "::set-output name=version::$(grep 'version: ' pubspec.yaml | cut -d ' ' -f2)"

      - name: Build AAB
        run: |
          flutter pub get
          flutter test
          flutter build appbundle --no-tree-shake-icons

          - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ steps.version.outputs.version }}
            release_name: Release ${{ steps.version.outputs.version }}
            draft: false
            prerelease: false

      - name: Upload AAB to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/app/outputs/bundle/release/app-release.aab
          asset_name: topics-release-${{ steps.version.outputs.version }}.aab
          asset_content_type: application/octet-stream

      - name: Set Google Client ID
        run: echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" > .env
